### ISSUE TITLE
【建议】如果使用诸如 json 格式的格式化数据保存就更好了

### ISSUE THREAD

**Issue by gingerhot** [sheepzh/poetry#6]
比如可以参考古诗词的项目，使用 json 格式保存：https://github.com/chinese-poetry/chinese-poetry

https://github.com/chinese-poetry/chinese-poetry/blob/master/mengxue/qianjiashi.json#L1-L15

使用结构化数据可以区分作者和内容等信息，方便使用。

**Comment by sheepzh** [comment]
请问您平时的开发环境是什么呢？后续会支持以脚本的方式进行导出，不过为了兼顾可读性，源文件仍然会是当前的格式。

**Comment by gingerhot** [comment]
> 请问您平时的开发环境是什么呢？后续会支持以脚本的方式进行导出，不过为了兼顾可读性，源文件仍然会是当前的格式。

我暂时还没有使用。如果使用的话，这个文本也是相对容易处理的。
但是如果作为数据源，肯定是使用结构化的格式存储更好一些。比如使用 json 格式，可读性也并不会很差。
只是建议一下，因为随着数据越来越多，再转换格式的话需要处理的文本就更多了。
